---
apiVersion: v1
kind: Service
metadata:
  name: condor
spec:
  selector:
    app: condor
  type: ClusterIP
  ports:
    - name: shared-port
      port: 9618
      targetPort: 9618
      protocol: TCP
