name: 'Make Artifact Hash'
description: 'Create a hash for a job run that can be used to correlate it to its artifacts'
outputs:
  hash:
    description: 'The hash of the matrix'
    value: ${{ steps.create-matrix-hash.outputs.HASH }}
runs:
  using: composite
  steps:
    - name: Create Matrix Hash
      id: create-matrix-hash
      env:
        MATRIX: ${{ toJson(matrix) }}
      shell: bash
      run: echo "HASH=$(echo -n "$MATRIX" | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
