name: Test Harness
on:
  workflow_call:
    inputs:
      testName:
        description: 'The name of the Go test to run'
        type: string
        required: true
      testEnv: 
        description: 'The matrix to use for the test, as a JSON string'
        type: string
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    name: Run ${{ inputs.testName }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    # Populate metadata into the step name for display on the web UI
    - id: serialize-matrix
      uses: ./.github/actions/serialize-matrix
    - name: 'Job Matrix: ${{ steps.serialize-matrix.outputs.matrixJson }}'
      shell: bash
      run: 'true'
      
    # Actual test contents
    - name: Setup environment
      uses: ./.github/actions/setup
    - name: 'Test ${{ inputs.testName }} with ${{ steps.serialize-matrix.outputs.matrixJson }}'
      env: ${{ fromJSON(inputs.testEnv) }}
      run: go test ./test -v -count 1 -run ${{ inputs.testName }} -timeout 15m
      
    # Upload artifacts after the fact, named such that they can be correlated to the test run using the hash
    - id: make-artifact-hash
      if: always()
      uses: ./.github/actions/make-artifact-hash
    - name: Upload Test Logs for ${{ steps.make-artifact-hash.outputs.HASH }}
      if: always()
      uses: ./.github/actions/upload-artifacts-by-hash
      with:
        prefix: ospool-ep
        hash: ${{ steps.make-artifact-hash.outputs.HASH }}
