name: Test Harness
on:
  workflow_call:
    inputs:
      testName:
        description: 'The name of the Go test to run'
        type: string
        required: true
      testEnv: 
        description: 'The Environment to use for the test, encoded as a YAML string'
        type: string
        required: true
      setupScript:
        description: 'Setup script to run before the test'
        type: string
        required: false
      setupEnv:
        description: 'Environment of the setup script, encoded as a YAML string'
        type: string
        required: false
        default: '{}'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    name: Run Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Convert inputs to JSON
      id: yaml-to-json-inputs
      shell: bash
      env:
        TEST_ENV_YAML: ${{ inputs.testEnv }}
        SETUP_ENV_YAML: ${{ inputs.setupEnv }}
      run: |
        echo "TEST_ENV=$(echo "$TEST_ENV_YAML" | yq -o json | tr -d '\n')" >> $GITHUB_OUTPUT
        echo "SETUP_ENV=$(echo "$SETUP_ENV_YAML" | yq -o json | tr -d '\n')" >> $GITHUB_OUTPUT

    # Populate metadata into the step name for display on the web UI
    - id: serialize-env
      env:
        TEST_ENV: ${{ steps.yaml-to-json-inputs.outputs.TEST_ENV }}
      shell: bash
      run: echo "TEST_ENV=$(echo -n "$TEST_ENV" | tr '\n' ' ' | sed 's/\s\+/ /g')" >> $GITHUB_OUTPUT
    - name: 'Job Matrix: ${{ steps.serialize-env.outputs.TEST_ENV }}'
      shell: bash
      run: 'true'
      
    # Actual test contents
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'
        cache: true
        cache-dependency-path: go.sum

    - name: Test Setup Scripts
      if: ${{ inputs.setupScript != '' }}
      shell: bash
      env: ${{ fromJSON(steps.yaml-to-json-inputs.outputs.SETUP_ENV) }}  
      run: ${{ inputs.setupScript }}
      
    - name: 'Test ${{ inputs.testName }}'
      env: ${{ fromJSON(steps.yaml-to-json-inputs.outputs.TEST_ENV) }}
      run: go test ./test -v -count 1 -run ${{ inputs.testName }} -timeout 15m
      
    # Upload artifacts after the fact, named such that they can be correlated to the test run using the hash of the test environment
    - name: Create Test Env Hash
      if: always()
      id: create-testenv-hash
      env:
        TEST_ENV: ${{ inputs.testEnv }}
      shell: bash
      run: echo "HASH=$(echo -n "$TEST_ENV" | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
      
    - name: Upload Test Logs of ${{ steps.create-testenv-hash.outputs.HASH }}
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.testName }}-${{ steps.create-testenv-hash.outputs.HASH }}
        path: /tmp/k8s-tests
        retention-days: 5
