name: OSPool EP Tests
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test-ospool-ep:
    strategy:
      fail-fast: false
      matrix:
        cvmfsType: ['cvmfsexec', 'cvmfs-bind']
        ospoolEPVersion: ['25-release', '25-testing']
        include:
          - ospoolEPVersion: 25-release
            cmVersion: 25.0-el9
          - ospoolEPVersion: 25-testing
            cmVersion: 25.x-el9
    runs-on: ubuntu-22.04
    name: Run OSPool EP test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    #- name: Setup environment
    #  uses: ./.github/actions/setup
    - name: 'Test OSPool EP with ${{ matrix.cvmfsType }}, ${{ matrix.ospoolEPVersion }}, ${{ matrix.cmVersion }}'
      env:
        OSPOOL_EP_OSPoolEPTag: ${{ matrix.ospoolEPVersion }}
        OSPOOL_EP_CMTag: ${{ matrix.cmVersion }}
        OSPOOL_EP_CvmfsType: ${{ matrix.cvmfsType }}
      # run: go test ./test -v -count 1 -run TestOSPoolEP -timeout 15m
      run: |
        mkdir -p /tmp/k8s-tests
        echo "(Not) Running OSPool EP tests with cvmfsType=${{ matrix.cvmfsType }}, ospoolEPVersion=${{ matrix.ospoolEPVersion }}, cmVersion=${{ matrix.cmVersion }}" > /tmp/k8s-tests/test.log
    - name: Create Matrix Hash
      id: create-matrix-hash
      env:
        MATRIX: ${{ toJson(matrix) }}
      shell: bash
      run: echo "HASH=$(echo -n "$MATRIX" | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
    - name: Upload Test Logs for ${{ steps.create-matrix-hash.outputs.HASH }}
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}-${{ steps.create-matrix-hash.outputs.HASH }}
        path: /tmp/k8s-tests
        retention-days: 5
