name: Pelican Tests
on:
  workflow_call:
  workflow_dispatch:
jobs:
  generate-pelican-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'
    - name: Generate version matrix
      id: matrix
      run: echo "matrix=$(go run ./scripts/cmd/pelicanVersionMatrix)" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-pelican:
    needs: generate-pelican-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-pelican-matrix.outputs.matrix) }}
    runs-on: ubuntu-22.04
    name: Run Pelican tests
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup environment
      uses: ./.github/actions/setup
    - name: Cache Pelican CLI
      uses: actions/cache@v4
      with:
        path: /tmp/pelican-cache
        key: pelican-cli-${{ matrix.clientVersion }}
    - name: Install Pelican CLI
      run: |
        VERSION="${{ matrix.clientVersion }}"
        VERSION="${VERSION#v}"
        DEB_VERSION=pelican_$(echo "$VERSION" | sed 's/-rc/.rc/')-1_amd64.deb
        CACHE_PATH="/tmp/pelican-cache/${DEB_VERSION}"
        if [ ! -f "${CACHE_PATH}" ]; then
          mkdir -p /tmp/pelican-cache
          wget -O "${CACHE_PATH}" "https://dl.pelicanplatform.org/${VERSION}/${DEB_VERSION}"
        fi
        sudo dpkg -i "${CACHE_PATH}"
    - name: 'Test Pelican'
      env:
        PELICAN_ClientTag:  v7.26.0-rc.0 # client docker image not supported in versions prior to v7.26.0-rc.0
        PELICAN_CacheTag: ${{ matrix.cacheVersion }}
        PELICAN_OriginTag: ${{ matrix.originVersion }}
        PELICAN_RegistryTag: ${{ matrix.registryVersion }}
        PELICAN_DirectorTag: ${{ matrix.directorVersion }}
      run: go test ./test -v -count 1 -run TestPelican -timeout 15m
    - name: 'Upload Test Logs'
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pelican-${{ matrix.clientVersion }}-${{ matrix.cacheVersion }}-${{ matrix.originVersion }}-${{ matrix.registryVersion }}-${{ matrix.directorVersion }}
        path: /tmp/k8s-tests
        retention-days: 5
