name: Test Harness
on:
  workflow_call:
    inputs:
      testName:
        description: 'The name of the Go test to run'
        type: string
        required: true
      testEnv: 
        description: 'The Environment to use for the test, encoded as a JSON string'
        type: string
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    name: Run ${{ inputs.testName }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    # Populate metadata into the step name for display on the web UI
    - id: serialize-env
      env:
        TEST_ENV: ${{ inputs.testEnv }}
      shell: bash
      run: echo "TEST_ENV=$(echo -n "$TEST_ENV" | tr '\n' ' ' | sed 's/\s\+/ /g')" >> $GITHUB_OUTPUT
    - name: 'Job Matrix: ${{ steps.serialize-env.outputs.TEST_ENV }}'
      shell: bash
      run: 'true'
      
    # Actual test contents
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'
        cache: true
        cache-dependency-path: go.sum

    - name: 'Test ${{ inputs.testName }} with ${{ steps.serialize-matrix.outputs.matrixJson }}'
      env: ${{ fromJSON(inputs.testEnv) }}
      run: go test ./test -v -count 1 -run ${{ inputs.testName }} -timeout 15m
      
    # Upload artifacts after the fact, named such that they can be correlated to the test run using the hash of the test environment
    - name: Create Test Env Hash
      if: always()
      id: create-testenv-hash
      env:
        TEST_ENV: ${{ inputs.testEnv }}
      shell: bash
      run: echo "HASH=$(echo -n "$TEST_ENV" | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
      
    - name: Upload Test Logs of ${{ steps.create-testenv-hash.outputs.HASH }}
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.testName }}-${{ steps.create-testenv-hash.outputs.HASH }}
        path: /tmp/k8s-tests
        retention-days: 5
