name: 'Serialize Matrix'
description: Serialize the job's matrix into a step name so that it can be parsed later for web display.
outputs:
  matrixJson:
    description: 'JSON serialization of the job matrix'
    value: ${{ steps.serialize-matrix-json.outputs.MATRIX_JSON }}
runs:
  using: composite
  steps:
    - name: Serialize Matrix JSON
      id: serialize-matrix-json
      env:
        MATRIX: ${{ toJson(matrix) }}
      shell: bash
      run: echo "MATRIX_JSON=$(echo -n "$MATRIX" | tr '\n' ' ' | sed 's/\s\+/ /g')" >> $GITHUB_OUTPUT
